Tests
StarMindz/School-Library-on-Ruby- pull request #6
Opened 2023-01-12 20:38 UTC by StarMindz

We created tests for all the Classes 
All tests were implemented using RSpec

2023-01-12 21:06 UTC, DammyShittu requested changes
Hi @StarMindz and @Goruchie,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 21:06 UTC, DammyShittu commented on README.md
> +- Show persons.
- [ ] Kindly add tests for the Person class. Remember to add tests for custom `add_rentals` and `can_use_services?` methods.

2023-01-12 21:06 UTC, DammyShittu commented on specs/book_spec.rb
> +end
- [ ] Kindly add tests for the `add_rentals` method in the Book class

2023-01-12 21:06 UTC, DammyShittu commented on specs/student_spec.rb
> +  end
- [ ] Kindly add tests for the `add_class` and `play_hooky` methods in the Student class

2023-01-13 13:33 UTC, danmainah reviewed
Hi @StarMindz and @Goruchie , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 14:48 UTC, merged